version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: tu_password_segura
      POSTGRES_DB: coffee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # expone PostgreSQL a tu PC

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data:
