services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: tu_password_segura
      POSTGRES_DB: coffee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "3000:3000"     # tu app Next
      - "5555:5555"     # Prisma Studio
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules   # 🔑 evita que se pisen las dependencias instaladas en la imagen
    command: npm run dev

volumes:
  postgres_data:

